##### Author: Divyabrata Das Gupta
##### Gmail ID: shubhodivgupta@gmail.com
##### Date Last Modified: 28th February, 2021

### Ques 1: Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

###### HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [4]:
import numpy as np

In [30]:
def my_Vander(in_vec=[],N=len(in_vec),increasing=False):
    in_vec=np.array(in_vec)
    k=[[]]
    if (increasing):
        k=np.column_stack([in_vec**(N-1-i) for i in range(N-1,-1,-1)])
    else:
        k=np.column_stack([in_vec**(N-1-i) for i in range(N)])
    return k

In [5]:
print("Enter the input vector\n(Enter 'end' to mark end of list):")
in_vec=[]
i=1
while(True):
    try:

        in_vec.append(int(input("Enter {}th list item: ".format(i))))
        i+=1
    except Exception as e:
                      break


Enter the input vector
(Enter 'end' to mark end of list):
Enter 1th list item: 1
Enter 2th list item: 2
Enter 3th list item: 3
Enter 4th list item: 4
Enter 5th list item: 5
Enter 6th list item: end


In [6]:
print(np.vander(in_vec,increasing=False),end='\n'*3)
print(np.vander(in_vec,N=6,increasing=True))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]


In [31]:
print(my_Vander(in_vec),end='\n'*3)
print(my_Vander(in_vec,6,increasing=True))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]


### Ques 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
##### The moving average sequence has n-k+1 elements as shown below:
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 

i 1 2 3 4 5 6 7 8 9 10

== == == == == == == == == == == == == 

Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 

y2 35 = (20+30+40+50)/4 

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.
##### Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [5]:
def mov_Avg(in_vec,K):
    avg_lst=[]
    for i in range(len(in_vec)-K+1):
        lst=in_vec[i:i+K]
        avg_lst.append(sum(lst)/K)
    return np.array(avg_lst)

In [6]:
st=input("Enter the input vector via comma separated numbers:\n(For Example: 1,2,3,4,5)\n")
in_vec=st.split(',')
in_vec=[int(i) for i in in_vec]
K=int(input("Enter Window size: "))
mov_Avg(in_vec,K)

Enter the input vector via comma separated numbers:
(For Example: 1,2,3,4,5)
3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150
Enter Window size: 3


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])